### PR TITLE
Add Support for Intel Joule

### PR DESCRIPTION
**Pull request by virgilvox**
Successfully can control pins. Please review :)

Will still need to update postInstall script, I believe MRAA install is a little different.

### CODE REVIEW

**Comment by rwaldron** [comment]
I merged this from your branch this morning <3

**Comment by virgilvox** [comment]
Ran the blink sketch again, had this problem. using "L1"

```
1472081253158 Device(s) Intel GT Tuchuck  
1472081253164 Connected Intel GT Tuchuck  
1472081253170 Repl Initialized  
>> Ready!!
/home/root/.node_app_slot/node_modules/galileo-io/lib/pin.js:163
      state.io = new IO.Gpio(this.gpio);
                 ^

Error: Illegal arguments for construction of _exports_Gpio
    at Error (native)
    at Pin.initialize (/home/root/.node_app_slot/node_modules/galileo-io/lib/pin.js:163:18)
    at Pin.Object.create.direction.set (/home/root/.node_app_slot/node_modules/galileo-io/lib/pin.js:144:14)
    at Pin.Object.create.mode.set (/home/root/.node_app_slot/node_modules/galileo-io/lib/pin.js:107:26)
    at Galileo.pinMode (/home/root/.node_app_slot/node_modules/galileo-io/lib/index.js:485:28)
    at Led.Controllers.DEFAULT.initialize.value (/home/root/.node_app_slot/node_modules/johnny-five/lib/led/led.js:78:17)
    at new Led (/home/root/.node_app_slot/node_modules/johnny-five/lib/led/led.js:203:10)
    at Board.<anonymous> (/home/root/.node_app_slot/main.js:11:13)
    at emitNone (events.js:72:20)
    at Board.emit (events.js:166:7)

```

**Comment by rwaldron** [comment]
I hit this as well and determined that it's not a bug in Johnny-Five or Galileo-IO. I then filed this: https://github.com/intel-iot-devkit/mraa/issues/570 and it was confirmed. LED100, 101, 102 don't work.

**Comment by virgilvox** [comment]
Can confirm. Other pins work fine. I had the LED work briefly - same way you did. This might explain why my board crashed then set itself to a sleep mode and I had to hold the power button to wake it..

**Comment by rwaldron** [comment]
> Can confirm. Other pins work fine. I had the LED work briefly - same way you did. This might explain why my board crashed then set itself to a sleep mode and I had to hold the power button to wake it..

Interesting! I assumed my crash was unrelated, but maybe it was?

**Pull request closed without merging**
